name: ci-wf
on: 
  push:
    branches: 
      - develop
  pull_request: 
    branches: 
      - develop
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome steep
        run:  echo "Welcome to Actions"
      - name: Checkout Repository
        uses: actions/checkoput@v4
      - name: Repository Information
        run: |
          echo "Repository Name: ${{github.repository}}" 
          echo "Type of Event: ${{github.event_name}}"
          git --version
          git branch
          git log